CREATE TABLE default.y_train_pretty
(
    `DT` DateTime,
    `ИМЯ МАШИНЫ` String,
    `ROW_IDX` Int64,
    `DATASET_IDX` Int64,
    `ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ Т.1` Nullable(Float32),
    `ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ Т.2` Nullable(Float32),
    `ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ Т.3` Nullable(Float32),
    `ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ Т.4` Nullable(Float32),
    `ГАЗОВАЯ ЗАДВИЖКА` Nullable(Float32),
    `ГСМ` Nullable(Float32),
    `ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА` Nullable(Float32),
    `ДВИГАТЕЛЬ РЕЗЕРВНОГО МАСЛОНАСОСА` Nullable(Float32),
    `ЗАДВИЖКА` Nullable(Float32),
    `ЗАП. И РЕГ. АРМАТУРА` Nullable(Float32),
    `ЗАПОРНАЯ АРМАТУРА` Nullable(Float32),
    `КЛ1 ТР ДО ЭД` Nullable(Float32),
    `КЛ2 ТР ДО ЭД` Nullable(Float32),
    `КОЖУХ МУФТЫ` Nullable(Float32),
    `КОРПУС` Nullable(Float32),
    `МАСЛОБАК` Nullable(Float32),
    `МАСЛОНАСОС РАБОЧИЙ` Nullable(Float32),
    `МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.)` Nullable(Float32),
    `МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (РЕЗ.)` Nullable(Float32),
    `МАСЛООХЛАДИТЕЛЬ М-05-1` Nullable(Float32),
    `МАСЛОПРОВОДЫ` Nullable(Float32),
    `МАСЛОСТАНЦИЯ ЖИДКОЙ СМАЗКИ` Nullable(Float32),
    `МАСЛЯНЫЙ ФИЛЬТР` Nullable(Float32),
    `МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ` Nullable(Float32),
    `ПОДШИПНИК ОПОРНО-УПОРНЫЙ` Nullable(Float32),
    `ПОДШИПНИК ОПОРНЫЙ №1` Nullable(Float32),
    `ПОДШИПНИК ОПОРНЫЙ №2` Nullable(Float32),
    `ПОДШИПНИК ОПОРНЫЙ` Nullable(Float32),
    `РЕГУЛИРУЮЩАЯ АППАРАТУРА` Nullable(Float32),
    `РЕДУКТОР ГАЗ. ЗАДВИЖКИ` Nullable(Float32),
    `РОТОР` Nullable(Float32),
    `САПФИР 22 МДД ПЕРЕПАД ДАВЛ. НА ЦИКЛОНЕ` Nullable(Float32),
    `САПФИР 22 МДД РАЗРЕЖЕНИЕ В КОЛЛЕКТОРЕ` Nullable(Float32),
    `ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ1` Nullable(Float32),
    `ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ2` Nullable(Float32),
    `ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ СПВД-М10-400-5` Nullable(Float32),
    `ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ВУ1` Nullable(Float32),
    `ТР-Р ТМ-4000-10/6` Nullable(Float32),
    `ТР-Р ТМ-6300-10/6` Nullable(Float32),
    `ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.3` Nullable(Float32),
    `ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.4` Nullable(Float32),
    `ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1` Nullable(Float32),
    `ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2` Nullable(Float32),
    `ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО` Nullable(Float32),
    `УЛИТА` Nullable(Float32),
    `ЭКСГАУСТЕР А/М` Nullable(Float32),
    `ЭКСГАУСТЕР Н-8000 А/М` Nullable(Float32),
    `ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ` Nullable(Float32),
    `ЭЛЕКТРОАППАРАТУРА` Nullable(Float32),
    `ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4` Nullable(Float32),
    `ЭЛЕКТРООБОРУДОВАНИЯ` Nullable(Float32),
)
ENGINE = MergeTree
ORDER BY (`DT`, `ИМЯ МАШИНЫ`)
SETTINGS index_granularity = 8192;

CREATE TABLE default.x_train_pretty
(
    `DT` DateTime,
    `ИМЯ МАШИНЫ` String,
    `ROW_IDX` Int64,
    `DATASET_IDX` Int64,
    `ТОК РОТОРА 1` Nullable(Float32),
    `ТОК РОТОРА 2` Nullable(Float32),
    `ТОК СТАТОРА` Nullable(Float32),
    `ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4` Nullable(Float32),
    `ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ` Nullable(Float32),
    `ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 1` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 2` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 3` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 4` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.` Nullable(Float32),
)
ENGINE = MergeTree
ORDER BY (`DT`, `ИМЯ МАШИНЫ`)
SETTINGS index_granularity = 8192;

CREATE TABLE default.x_test_pretty
(
    `DT` DateTime,
    `ИМЯ МАШИНЫ` String,
    `ROW_IDX` Int64,
    `DATASET_IDX` Int64,
    `ТОК РОТОРА 1` Nullable(Float32),
    `ТОК РОТОРА 2` Nullable(Float32),
    `ТОК СТАТОРА` Nullable(Float32),
    `ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3` Nullable(Float32),
    `ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4` Nullable(Float32),
    `ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ` Nullable(Float32),
    `ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 1` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 2` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 3` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 4` Nullable(Float32),
    `ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.` Nullable(Float32),
)
ENGINE = MergeTree
ORDER BY (`DT`, `ИМЯ МАШИНЫ`)
SETTINGS index_granularity = 8192;
