version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '1111:3001'
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - API_PREFIX=/api
      - DB_URL=postgresql://postgres:postgres@postgres:5432/koa_prisma_project
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=koa_prisma_project
    ports:
      - '5432:1234'

volumes:
  postgres:
